# Generated by Django 5.0.3 on 2024-04-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopit',
            name='img',
            field=models.ImageField(upload_to='shopit/'),
        ),
        migrations.AlterField(
            model_name='shopit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, max_length=10),
        ),
        migrations.AlterField(
            model_name='shopit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
